# Generated by Django 4.2.24 on 2025-09-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_at_purchase',
        ),
    ]
