# Generated by Django 4.2.24 on 2025-11-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
